CREATE TABLE IF NOT EXISTS appointments_rds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  requestId VARCHAR(64) NOT NULL UNIQUE,
  insuredId CHAR(5) NOT NULL,
  scheduleId INT NOT NULL,
  countryISO ENUM('PE','CL') NOT NULL,
  centerId INT NULL,
  specialtyId INT NULL,
  medicId INT NULL,
  date DATETIME NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
